// server/buildReelData.js — exports the REAL reel strips and symbol->art
// mappings from models/modelA.js and models/modelB.js (unmodified) as a
// static client-side data file. The client only ever uses this for the
// spinning-animation visuals; every spin OUTCOME (which stop each reel lands
// on, every win, every feature draw) comes from the server. Run after any
// change to the models; `npm run build:reeldata`.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { A, A_BASE_STRIPS, A_FREE_STRIPS } from '../../models/modelA.js';
import { B, B_STRIPS } from '../../models/modelB.js';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

// Mid/low symbols are original pictorial icons (not playing-card ranks),
// ordered by pay tier: nugget (highest) down to lasso (lowest).
const ART_A = { [A.W]: 'bull', [A.S]: 'gate', [A.C]: 'coin', [A.H1]: 'horseshoe', [A.H2]: 'cactus', [A.H3]: 'mesa', [A.AA]: 'nugget', [A.KK]: 'spur', [A.QQ]: 'lantern', [A.JJ]: 'wheel', [A.TT]: 'canteen', [A.NN]: 'lasso' };
const ART_B = { [B.W]: 'bull', [B.M]: 'moneybull', [B.H1]: 'horseshoe', [B.H2]: 'cactus', [B.H3]: 'mesa', [B.AA]: 'nugget', [B.KK]: 'spur', [B.QQ]: 'lantern', [B.JJ]: 'wheel', [B.TT]: 'canteen', [B.NN]: 'lasso' };

const data = {
  A: { W: A.W, S: A.S, C: A.C, art: ART_A, baseStrips: A_BASE_STRIPS, freeStrips: A_FREE_STRIPS },
  B: { W: B.W, M: B.M, art: ART_B, strips: B_STRIPS },
};

const out = `// public/js/reeldata.js — GENERATED by server/buildReelData.js from the
// real models/modelA.js and models/modelB.js. Do not edit by hand; visuals
// only — spin outcomes always come from the server.
export const REELDATA = ${JSON.stringify(data)};
`;
const outPath = path.join(ROOT, 'public', 'js', 'reeldata.js');
fs.writeFileSync(outPath, out);
console.log(`wrote ${outPath} (${(out.length / 1024).toFixed(1)} KB)`);
